import { defineEventCatalog } from "../../event-api";

export const EVENT_CARDS = defineEventCatalog({
  thu_arrival: {
    title: "八月十六日：战前准备",
    body: "两校的迎新组织、宿舍值守与校园服务系统提前进入准备状态。真正的新生报到尚未开始。",
    effect: "双方完成初始部署；清华保留既有预备兵力优势。",
    quadrant: "arrival",
    date: "架空战役序章 · 2026年8月16日",
    sourceType: "war_scenario",
  },
  pku_jianghuai_welcome: {
    title: "江淮晚会：缘起江淮",
    body: "8月17日晚，江淮发展研究会与校友力量先行迎接安徽新生。灯火亮起，燕园战役的序幕由一场迎新晚会拉开。",
    effect: "北大获得20战略资源，外园宿舍意志提升10%，持续48小时。",
    quadrant: "arrival",
    date: "年度迎新活动窗口 · 2026年8月17日晚",
    sourceType: "annual_activity",
    sourceUrl: "https://news.pku.edu.cn/xwzh/129-115581.htm",
  },
  night_mobilization: {
    title: "路灯下的动员",
    body: "两校社团在夜色中清点物资，临时通讯网开始覆盖主要道路。",
    effect: "双方获得20战略资源。",
    quadrant: "march",
    date: "2026年8月17日",
  },
  morning_class: {
    title: "上早八",
    body: "八点钟声响起，战线上的学生突然想起还有一节无法逃掉的早课。道路与教室同时拥挤起来。",
    effect: "持续1个游戏小时：全体士兵移动速度与攻击力下降28%。",
    quadrant: "classroom",
    date: "每日08:00",
  },
  pku_arrival: {
    title: "八月十八日：北大本科新生报到",
    body: "按照北京大学迎新安排，本科新生正式进入燕园。宿舍区人声渐盛，原有兵力差被迅速抹平。",
    effect: "北大补充兵力至与清华大致均衡。",
    quadrant: "arrival",
    date: "2026年8月18日",
    sourceType: "calendar",
    sourceUrl: "https://fresh.pku.edu.cn/",
  },
  war_begins: {
    title: "八月十九日：校门开放",
    body: "此前的对峙宣告结束。巡逻队越过校园边界，第一批正式作战命令开始生效。",
    effect: "双方解除交战限制，清华战略AI开始行动。",
    quadrant: "march",
    date: "2026年8月19日",
  },
  qz_approach: {
    title: "人往高走，水向下流",
    body: "求真书院附近传来紧急动员。走廊、宿舍与课堂中的预备力量突然汇集。",
    effect: "求真书院附近出现清华援军；北大前锋冻结1个游戏日。",
    quadrant: "classroom",
    date: "战时特别报道",
    sourceType: "war_scenario",
  },
  pku_advantage: {
    title: "這會損害你們的數學思維",
    body: "面对不断扩大的战线，一份措辞严厉的内部讲话被迅速传遍校园。",
    effect: "前线北大单位压制力降低10%。",
    quadrant: "classroom",
    date: "战时特别报道",
  },
  qz_captured: {
    title: "我宣布你們已經不是我的學生了",
    body: "北大攻势即将完成占领时，一场戏剧性的身份重组提前发生，前线队伍陷入混乱。",
    effect: "首次攻势被阻止；求真书院仍归清华，附近北大单位转为清华单位。",
    quadrant: "classroom",
    date: "终局广播",
    sourceType: "war_scenario",
  },
  yuanpei_attack: {
    title: "为了自由！",
    body: "元培学院俄文楼遭到进攻。各院系学生沿湖畔道路赶来，临时防线在学院办公区周围形成。",
    effect: "元培附近增兵，北大获得局部攻击加成并吸引附近援军。",
    quadrant: "march",
    date: "燕园紧急广播",
  },
  yuanpei_fallen: {
    title: "自由之门关闭",
    body: "元培学院俄文楼的最后一道防线被突破。战役结果在此刻写定，但校园中的兵线仍未停下。",
    effect:
      "清华取得战役胜利；游戏继续运行，除非一方被完全消灭，结果不再改变。",
    quadrant: "classroom",
    date: "燕园终局广播",
  },
  lake_awakened: {
    title: "胸中未名水",
    body: "敌军接近未名湖，湖畔的沉静被打破。消息传遍燕园，士气陡然上升。",
    effect: "全体北大单位永久获得15%攻击加成。",
    quadrant: "lake",
    date: "燕园特别报道",
  },
  double_fei: {
    title: "双菲学校",
    body: "北大数学科学学院遭到进攻，一则来历不明的数学评价在前线传播，求真方向的队伍陷入争论。",
    effect: "求真书院附近清华单位移动速度与攻击力降低50%。",
    quadrant: "classroom",
    date: "数学战线快讯",
    sourceType: "easter_egg",
  },
  thu_ustc: {
    title: "清华转进中科大",
    body: "持续的进攻使清华战时委员会作出惊人决定：剩余防线以“中科大远征校区”的名义继续作战。",
    effect: "清华阵营更名为中科大；攻击、移动、防守、意志与生产获得长期加成。",
    quadrant: "march",
    date: "特别彩蛋",
    sourceType: "easter_egg",
  },
  zju_invasion: {
    title: "浙大入侵",
    body: "战局长期僵持后，一支自称“紫金港观察团”的队伍从地图边缘出现，并迅速选择较弱一方作为临时盟友。",
    effect: "较弱阵营获得一支带特殊外观的浙大先遣队，并立即向前线推进。",
    quadrant: "arrival",
    date: "特别彩蛋",
    sourceType: "easter_egg",
  },
  first_camp: {
    title: "没有校门的据点",
    body: "第一座临时营地在道路之外落成，折叠桌、路灯与补给箱构成了新的前线。",
    effect: "解锁营地补给：附近北大单位缓慢恢复补给。",
    quadrant: "arrival",
    date: "前线记录",
  },
  first_blood: {
    title: "第一份伤亡名单",
    body: "双方终于意识到，这不再只是地图上的箭头。战报开始记录每一次损失。",
    effect: "双方攻击节奏暂时降低，持续12小时。",
    quadrant: "classroom",
    date: "战地简报",
  },
  thu_alarm: {
    title: "清华园墙告急",
    body: "数个外围据点连续失守，清华开始收缩战线，并向求真书院方向重新集结。",
    effect: "求真防区获得额外守军与补给。",
    quadrant: "march",
    date: "清华战时委员会",
  },
  thu_morning_run: {
    title: "八月三十日：清华夜跑",
    body: "午夜的清华园突然响起整齐脚步声。队伍在凌晨沿校园边缘据点循环行进，速度惊人，但进攻动作明显变形。",
    effect:
      "8月30日00:00—04:00：清华移速+50%、攻击-10%、意志+20%；北大攻击+20%、意志+5%。仅影响当前单位。",
    quadrant: "march",
    date: "2026年8月30日 00:00",
  },
  pku_librarian: {
    title: "图书管理员",
    body: "图书馆进入战斗范围后，馆藏与目录被迅速转入战时保护。消息传遍燕园。",
    effect: "北大当前全体单位攻击+10%、意志+50%，持续24小时。",
    quadrant: "classroom",
    date: "图书馆战线",
  },
  two_bombs_one_satellite: {
    title: "两弹一星",
    body: "物理学院遭到实际进攻。两弹元勋的历史被重新讲述，前线随即爆发压倒性的反击。",
    effect:
      "附近清华单位遭到毁灭性打击；北大当前全体单位意志+50%，持续24小时。",
    quadrant: "classroom",
    date: "物理学院战线",
  },
  chemistry_century: {
    title: "百年化学",
    body: "化学学院实验楼进入战斗范围，应急实验组以烟幕和材料储备支援防线。",
    effect: "附近清华单位补给大幅下降；北大当前单位意志+20%，持续18小时。",
    quadrant: "classroom",
    date: "化学学院战线",
  },
});
