'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';

type Team = 'pku' | 'thu';
type Stance = 'defend' | 'guard' | 'standby';
type SiteKind = 'dorm' | 'teaching' | 'gate' | 'target';
type SiteState = { id: number; name: string; team: Team; x: number; z: number; type: SiteKind; stance: Stance; supply: number; orderTarget?: number };
type UnitState = { id: number; team: Team; x: number; z: number; tx: number; tz: number; hp: number; supply: number; siteId: number; targetSiteId?: number };
type GameData = { timeOfDay: number; resources: Record<Team, number>; deaths: Record<Team, number>; sites: SiteState[]; units: UnitState[] };
type Snapshot = GameData & { version: 1; name: string; savedAt: number };

const SAVE_KEY = 'qingbei-webgl-saves-v1';
const TEAM_COLOR: Record<Team, number> = { pku: 0xa20d27, thu: 0x6f3291 };

const seeds: Omit<SiteState, 'id' | 'stance' | 'supply'>[] = [
  { name:'北大西门',team:'pku',x:-43,z:26,type:'gate' },{ name:'北大东门',team:'pku',x:-7,z:15,type:'gate' },{ name:'北京大学图书馆',team:'pku',x:-19,z:19,type:'teaching' },{ name:'博雅塔',team:'pku',x:-25,z:7,type:'teaching' },
  { name:'百周年纪念讲堂',team:'pku',x:-12,z:27,type:'teaching' },{ name:'北京国际数学研究中心',team:'pku',x:-35,z:5,type:'teaching' },{ name:'文博楼',team:'pku',x:-41,z:8,type:'teaching' },{ name:'生物技术楼',team:'pku',x:-36,z:12,type:'teaching' },
  { name:'李兆基人文学苑',team:'pku',x:-30,z:11,type:'teaching' },{ name:'经济学院',team:'pku',x:-23,z:12,type:'teaching' },{ name:'政府管理大楼',team:'pku',x:-11,z:6,type:'teaching' },{ name:'理科一号楼',team:'pku',x:-16,z:8,type:'teaching' },
  { name:'理科二号楼',team:'pku',x:-12,z:12,type:'teaching' },{ name:'理科三号楼',team:'pku',x:-8,z:8,type:'teaching' },{ name:'第一教学楼',team:'pku',x:-22,z:25,type:'teaching' },{ name:'第二教学楼',team:'pku',x:-17,z:24,type:'teaching' },
  { name:'燕园28楼',team:'pku',x:-39,z:30,type:'dorm' },{ name:'燕园29楼',team:'pku',x:-34,z:30,type:'dorm' },{ name:'燕园30楼',team:'pku',x:-29,z:31,type:'dorm' },{ name:'燕园31楼',team:'pku',x:-24,z:32,type:'dorm' },{ name:'燕园34A楼',team:'pku',x:-18,z:33,type:'dorm' },{ name:'燕园34B楼',team:'pku',x:-12,z:34,type:'dorm' },
  { name:'清华西门',team:'thu',x:2,z:5,type:'gate' },{ name:'二校门',team:'thu',x:10,z:1,type:'gate' },{ name:'清华学堂',team:'thu',x:16,z:-5,type:'teaching' },{ name:'大礼堂',team:'thu',x:22,z:-8,type:'teaching' },
  { name:'老图书馆',team:'thu',x:17,z:1,type:'teaching' },{ name:'科学馆',team:'thu',x:12,z:8,type:'teaching' },{ name:'主楼',team:'thu',x:31,z:3,type:'teaching' },{ name:'六教',team:'thu',x:23,z:13,type:'teaching' },
  { name:'新清华学堂',team:'thu',x:28,z:11,type:'teaching' },{ name:'艺术博物馆',team:'thu',x:38,z:14,type:'teaching' },{ name:'综合体育馆',team:'thu',x:25,z:-20,type:'teaching' },{ name:'校医院',team:'thu',x:8,z:15,type:'teaching' },
  { name:'紫荆1号楼',team:'thu',x:30,z:-24,type:'dorm' },{ name:'紫荆2号楼',team:'thu',x:35,z:-24,type:'dorm' },{ name:'紫荆3号楼',team:'thu',x:40,z:-23,type:'dorm' },{ name:'紫荆6号楼',team:'thu',x:29,z:-29,type:'dorm' },{ name:'紫荆9号楼',team:'thu',x:36,z:-29,type:'dorm' },{ name:'求真书院',team:'thu',x:43,z:-29,type:'target' },
  { name:'清华南门',team:'thu',x:22,z:26,type:'gate' },{ name:'清华东南门',team:'thu',x:45,z:22,type:'gate' },
];

function makeFreshGame(): GameData {
  const sites: SiteState[] = seeds.map((s,id)=>({...s,id,stance:'defend',supply:100}));
  const units: UnitState[]=[]; let uid=0;
  sites.forEach(s=>{const count=s.type==='dorm'?(s.team==='pku'?3:2):(s.team==='pku'?4:3);for(let i=0;i<count;i++){const a=i/count*Math.PI*2;units.push({id:uid++,team:s.team,x:s.x+Math.cos(a)*1.25,z:s.z+Math.sin(a)*1.25,tx:s.x,tz:s.z,hp:100,supply:100,siteId:s.id});}});
  return {timeOfDay:8.2,resources:{pku:180,thu:180},deaths:{pku:0,thu:0},sites,units};
}
function readSaves(): Snapshot[]{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'[]') as Snapshot[];}catch{return[];}}

export default function Game3D(){
  const hostRef=useRef<HTMLDivElement>(null);const gameRef=useRef<GameData>(makeFreshGame());const sceneApi=useRef<{sync:()=>void}|null>(null);
  const [saves,setSaves]=useState<Snapshot[]>([]);const [saveOpen,setSaveOpen]=useState(false);const [saveName,setSaveName]=useState('燕园远征');const [autoDay,setAutoDay]=useState(true);const autoDayRef=useRef(true);const [clock,setClock]=useState('08:12');const [selected,setSelected]=useState<number|null>(null);const [stats,setStats]=useState({pku:0,thu:0,pkuSites:0,thuSites:0});
  const selectedSite=selected==null?null:gameRef.current.sites[selected];
  const refreshSaves=useCallback(()=>setSaves(readSaves().sort((a,b)=>b.savedAt-a.savedAt)),[]);
  useEffect(()=>refreshSaves(),[refreshSaves]);useEffect(()=>{autoDayRef.current=autoDay;},[autoDay]);

  useEffect(()=>{
    const host=hostRef.current;if(!host)return;
    const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.appendChild(renderer.domElement);
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc5d8);scene.fog=new THREE.FogExp2(0x9fc5d8,.007);
    const camera=new THREE.PerspectiveCamera(42,host.clientWidth/host.clientHeight,.1,250);camera.position.set(0,74,74);camera.lookAt(0,0,4);
    const hemi=new THREE.HemisphereLight(0xcfe8ff,0x324226,1.9);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff0d0,3.4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;scene.add(sun);const moon=new THREE.DirectionalLight(0x91b7ff,.25);scene.add(moon);
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(110,82),new THREE.MeshStandardMaterial({color:0x718d58,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
    const roadMat=new THREE.MeshStandardMaterial({color:0xa99f88,roughness:.93});const addRoad=(x:number,z:number,w:number,d:number,r=0)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,.08,d),roadMat);m.position.set(x,.04,z);m.rotation.y=r;m.receiveShadow=true;scene.add(m);};addRoad(0,9,96,2.4,-.11);addRoad(15,-6,2.1,54,.03);addRoad(-24,22,42,1.9,-.1);addRoad(30,-21,31,1.8,.02);addRoad(-3,9,26,1.7,-.62);addRoad(32,8,1.7,40,-.08);addRoad(-31,15,1.5,30,.04);
    const buildingGroup=new THREE.Group();scene.add(buildingGroup);const unitGroup=new THREE.Group();scene.add(unitGroup);const siteObjects=new Map<number,THREE.Group>();const unitObjects=new Map<number,THREE.Group>();const windowMaterials:THREE.MeshStandardMaterial[]=[];
    const labelTexture=(text:string,color:string)=>{const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d')!;x.fillStyle='rgba(21,30,25,.86)';x.roundRect(4,4,504,88,16);x.fill();x.strokeStyle=color;x.lineWidth=5;x.stroke();x.fillStyle='#fff6dc';x.font='700 34px Microsoft YaHei';x.textAlign='center';x.fillText(text,256,61);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;};
    const rebuildBuildings=()=>{buildingGroup.clear();siteObjects.clear();windowMaterials.splice(0);gameRef.current.sites.forEach(site=>{const g=new THREE.Group();g.position.set(site.x,0,site.z);const isDorm=site.type==='dorm',isTarget=site.type==='target',w=isDorm?3.2:site.type==='gate'?2.7:3.8,d=isDorm?2.2:2.8,h=isDorm?2.6:site.type==='gate'?1.5:isTarget?4.7:3.6;
      const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:isTarget?0xc57c45:isDorm?0xb79b74:0x9da7a7,roughness:.78}));body.position.y=h/2;body.castShadow=true;body.receiveShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,1,4),new THREE.MeshStandardMaterial({color:isTarget?0xffb64d:0x70463b,roughness:.82}));roof.position.y=h+.45;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(roof);
      const wm=new THREE.MeshStandardMaterial({color:0x537080,emissive:0xffc56a,emissiveIntensity:0,roughness:.35});windowMaterials.push(wm);for(let y=.8;y<h-.25;y+=.72)for(const sx of [-1,1]){const win=new THREE.Mesh(new THREE.PlaneGeometry(.38,.28),wm);win.position.set(sx*.72,y,d/2+.012);g.add(win);}
      const ring=new THREE.Mesh(new THREE.RingGeometry(2.15,2.52,48),new THREE.MeshBasicMaterial({color:TEAM_COLOR[site.team],transparent:true,opacity:.9,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.07;g.add(ring);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:labelTexture(site.name,site.team==='pku'?'#df3b50':'#a569d0'),transparent:true,depthTest:false}));sprite.scale.set(5.8,1.08,1);sprite.position.y=h+1.75;g.add(sprite);g.traverse(o=>{o.userData.siteId=site.id;});buildingGroup.add(g);siteObjects.set(site.id,g);});};
    const tokenTex={} as Record<Team,THREE.CanvasTexture>;(['pku','thu'] as Team[]).forEach(team=>{const c=document.createElement('canvas');c.width=128;c.height=128;const x=c.getContext('2d')!;x.fillStyle=team==='pku'?'#a20d27':'#6f3291';x.beginPath();x.arc(64,64,58,0,Math.PI*2);x.fill();x.strokeStyle='#fff0cf';x.lineWidth=8;x.stroke();x.fillStyle='#fff8df';x.font='900 42px Microsoft YaHei';x.textAlign='center';x.fillText(team==='pku'?'北大':'清华',64,79);tokenTex[team]=new THREE.CanvasTexture(c);tokenTex[team].colorSpace=THREE.SRGBColorSpace;});
    const rebuildUnits=()=>{unitGroup.clear();unitObjects.clear();gameRef.current.units.forEach(u=>{const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.16,24),new THREE.MeshStandardMaterial({map:tokenTex[u.team],roughness:.48}));body.rotation.x=Math.PI/2;body.position.y=.62;body.castShadow=true;g.add(body);const lm=new THREE.MeshStandardMaterial({color:0x20231f}),lg=new THREE.CylinderGeometry(.045,.045,.55,6);[-1,1].forEach(s=>{const limb=new THREE.Mesh(lg,lm);limb.position.set(s*.35,.27,0);limb.rotation.z=s*.48;g.add(limb);});g.position.set(u.x,0,u.z);unitGroup.add(g);unitObjects.set(u.id,g);});};
    rebuildBuildings();rebuildUnits();
    const treeGroup=new THREE.Group();scene.add(treeGroup);let seed=91723;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const tg=new THREE.CylinderGeometry(.14,.2,1.8,7),tm=new THREE.MeshStandardMaterial({color:0x61412f,roughness:1}),cg=new THREE.SphereGeometry(1,10,8),cms=[0x315d36,0x467648,0x5b8a4e].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.92}));for(let i=0;i<260;i++){const x=-52+rnd()*104,z=-38+rnd()*76;if(gameRef.current.sites.some(s=>Math.hypot(s.x-x,s.z-z)<3.3)||Math.abs(z-(9-x*.11))<2.5)continue;const g=new THREE.Group(),tr=new THREE.Mesh(tg,tm);tr.position.y=.9;tr.castShadow=true;g.add(tr);cms.forEach((m,j)=>{const cr=new THREE.Mesh(cg,m);cr.scale.set(1.1-j*.18,.65,1.1-j*.18);cr.position.y=2+j*.62;cr.castShadow=true;g.add(cr);});g.position.set(x,0,z);treeGroup.add(g);}
    const lights:THREE.PointLight[]=[];[[-29,20],[-8,10],[8,8],[19,3],[31,-12],[39,-24],[22,18]].forEach(([x,z])=>{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.05,.07,2.4,6),new THREE.MeshStandardMaterial({color:0x353b37}));pole.position.set(x,1.2,z);scene.add(pole);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.16,8,6),new THREE.MeshStandardMaterial({color:0xffd98e,emissive:0xffb33b,emissiveIntensity:2}));bulb.position.set(x,2.4,z);scene.add(bulb);const l=new THREE.PointLight(0xffc66f,0,11,2);l.position.set(x,2.5,z);scene.add(l);lights.push(l);});
    const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down:{x:number;y:number;site?:number}|null=null;const hitSite=(ev:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=(ev.clientX-r.left)/r.width*2-1;mouse.y=-(ev.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(buildingGroup.children,true)[0];return hit?.object.userData.siteId as number|undefined;};renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,site:hitSite(e)};});renderer.domElement.addEventListener('pointerup',e=>{if(!down)return;const end=hitSite(e),moved=Math.hypot(e.clientX-down.x,e.clientY-down.y)>8;if(!moved&&down.site!=null)setSelected(down.site);if(moved&&down.site!=null&&end!=null&&end!==down.site){const source=gameRef.current.sites[down.site],target=gameRef.current.sites[end];if(source.team==='pku'){source.orderTarget=target.id;gameRef.current.units.filter(u=>u.team==='pku'&&u.siteId===source.id).forEach(u=>{u.targetSiteId=target.id;u.tx=target.x;u.tz=target.z;});}}down=null;});
    let raf=0,last=performance.now(),statAt=0;const animate=(now:number)=>{raf=requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;const g=gameRef.current;if(autoDayRef.current)g.timeOfDay=(g.timeOfDay+dt*.08)%24;const angle=(g.timeOfDay-6)/24*Math.PI*2,day=THREE.MathUtils.smoothstep(Math.sin(angle),-.12,.35),night=1-day;sun.position.set(Math.cos(angle)*55,Math.max(-4,Math.sin(angle)*55),25);sun.intensity=day*3.4;moon.position.set(-sun.position.x,Math.max(10,-sun.position.y),-25);moon.intensity=night*.6;hemi.intensity=.18+day*1.72;hemi.color.set(day>.35?0xcfe8ff:0x29436e);hemi.groundColor.set(day>.35?0x324226:0x101721);const sky=new THREE.Color(0x07101f).lerp(new THREE.Color(0x9fc5d8),day);scene.background=sky;(scene.fog as THREE.FogExp2).color.copy(sky);windowMaterials.forEach(m=>m.emissiveIntensity=night*3.2);lights.forEach(l=>l.intensity=night*15);renderer.toneMappingExposure=.72+day*.38;
      g.units.forEach(u=>{const mesh=unitObjects.get(u.id);if(!mesh)return;const dx=u.tx-u.x,dz=u.tz-u.z,dist=Math.hypot(dx,dz);if(dist>.18){const s=1.25*dt;u.x+=dx/dist*s;u.z+=dz/dist*s;mesh.position.set(u.x,0,u.z);mesh.rotation.y=Math.atan2(dx,dz);}});if(now-statAt>500){statAt=now;setStats({pku:g.units.filter(u=>u.team==='pku').length,thu:g.units.filter(u=>u.team==='thu').length,pkuSites:g.sites.filter(s=>s.team==='pku').length,thuSites:g.sites.filter(s=>s.team==='thu').length});const h=Math.floor(g.timeOfDay),m=Math.floor(g.timeOfDay%1*60);setClock(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);}renderer.render(scene,camera);};raf=requestAnimationFrame(animate);
    const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();};addEventListener('resize',resize);sceneApi.current={sync:()=>{rebuildBuildings();rebuildUnits();}};return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);renderer.dispose();if(renderer.domElement.parentNode===host)host.removeChild(renderer.domElement);};
  },[]);

  const saveGame=()=>{const name=saveName.trim()||`存档 ${new Date().toLocaleString('zh-CN')}`,snapshot:Snapshot={version:1,name,savedAt:Date.now(),...structuredClone(gameRef.current)},next=[snapshot,...readSaves().filter(s=>s.name!==name)].slice(0,12);localStorage.setItem(SAVE_KEY,JSON.stringify(next));refreshSaves();};
  const loadGame=(save:Snapshot)=>{const {timeOfDay,resources,deaths,sites,units}=structuredClone(save);gameRef.current={timeOfDay,resources,deaths,sites,units};sceneApi.current?.sync();setSelected(null);setSaveOpen(false);};
  const deleteSave=(savedAt:number)=>{const next=readSaves().filter(s=>s.savedAt!==savedAt);localStorage.setItem(SAVE_KEY,JSON.stringify(next));setSaves(next);};
  const newGame=()=>{gameRef.current=makeFreshGame();sceneApi.current?.sync();setSelected(null);};
  const stanceText=useMemo(()=>({defend:'🛡 防守',guard:'📡 守卫',standby:'⏸ 待命'}),[]);const setStance=(s:Stance)=>{if(!selectedSite||selectedSite.team!=='pku')return;selectedSite.stance=s;setSelected(selectedSite.id);};
  return <main className="game-shell"><div ref={hostRef} className="webgl-stage"/><header className="hud-top"><div><h1>燕园远征：求真书院</h1><p>WebGL 光影战略版</p></div><div className="time-pill"><span>{clock}</span><button onClick={()=>setAutoDay(v=>!v)}>{autoDay?'自动昼夜':'时间暂停'}</button></div><button className="save-main" onClick={()=>{refreshSaves();setSaveOpen(true);}}>存档管理</button></header><aside className="war-overview"><h2>总体战况</h2><div className="stat-grid"><span>总兵力</span><b className="red">{stats.pku}</b><b className="purple">{stats.thu}</b><span>控制据点</span><b className="red">{stats.pkuSites}</b><b className="purple">{stats.thuSites}</b><span>战略资源</span><b className="red">{Math.floor(gameRef.current.resources.pku)}</b><b className="purple">{Math.floor(gameRef.current.resources.thu)}</b><span>累计阵亡</span><b className="red">{gameRef.current.deaths.pku}</b><b className="purple">{gameRef.current.deaths.thu}</b></div><button onClick={newGame}>重新开始</button></aside>
    {selectedSite&&<section className="site-menu"><strong>{selectedSite.name}</strong><p className={selectedSite.team==='pku'?'red':'purple'}>{selectedSite.team==='pku'?'北大控制':'清华控制'} · 补给 {Math.round(selectedSite.supply)}</p><div>{(Object.keys(stanceText) as Stance[]).map(s=><button key={s} className={selectedSite.stance===s?'active':''} disabled={selectedSite.team!=='pku'} onClick={()=>setStance(s)}>{stanceText[s]}</button>)}</div><small>从此据点拖向友方可增援，拖向敌方可进攻</small></section>}
    <div className="day-slider"><span>昼夜</span><input aria-label="时间" type="range" min="0" max="24" step=".1" value={gameRef.current.timeOfDay} onChange={e=>{gameRef.current.timeOfDay=Number(e.target.value);setAutoDay(false);setClock(`${String(Math.floor(Number(e.target.value))).padStart(2,'0')}:00`);}}/></div>
    {saveOpen&&<div className="modal-backdrop" onMouseDown={()=>setSaveOpen(false)}><section className="save-modal" onMouseDown={e=>e.stopPropagation()}><div className="save-head"><div><small>本机存档</small><h2>战局档案馆</h2></div><button onClick={()=>setSaveOpen(false)}>×</button></div><div className="new-save"><input value={saveName} maxLength={24} onChange={e=>setSaveName(e.target.value)} placeholder="输入存档名称"/><button onClick={saveGame}>保存当前战局</button></div><div className="save-list">{!saves.length&&<p className="empty">暂无存档</p>}{saves.map(s=><article key={s.savedAt}><div><strong>{s.name}</strong><span>{new Date(s.savedAt).toLocaleString('zh-CN')} · {s.units.length}人 · {s.timeOfDay.toFixed(1)}时</span></div><button className="enter" onClick={()=>loadGame(s)}>进入</button><button className="delete" onClick={()=>deleteSave(s.savedAt)}>删除</button></article>)}</div><p className="save-note">存档保存在当前浏览器的本地存储中；清除浏览器数据会一并删除。</p></section></div>}
  </main>;
}
