'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { osmRegions } from '../src/osm-map-data';

type Team = 'pku' | 'thu';
type Stance = 'defend' | 'guard' | 'standby';
type RegionId = 'main' | 'newYanyuan' | 'medical' | 'wanliu';
type SiteKind = 'dorm' | 'teaching' | 'gate' | 'target';
type SiteState = { id: number; name: string; team: Team; x: number; z: number; type: SiteKind; stance: Stance; supply: number; orderTarget?: number };
type UnitState = { id: number; team: Team; x: number; z: number; tx: number; tz: number; hp: number; supply: number; siteId: number; targetSiteId?: number };
type GameData = { timeOfDay: number; resources: Record<Team, number>; deaths: Record<Team, number>; sites: SiteState[]; units: UnitState[] };
type Snapshot = GameData & { version: 1; name: string; savedAt: number };

const SAVE_KEY = 'qingbei-webgl-saves-v1';
const TEAM_COLOR: Record<Team, number> = { pku: 0xa20d27, thu: 0x6f3291 };

const seeds: Omit<SiteState, 'id' | 'stance' | 'supply'>[] = [
  { name:'北大西门',team:'pku',x:-43,z:26,type:'gate' },{ name:'北大东门',team:'pku',x:-20.8,z:17.2,type:'gate' },{ name:'北京大学图书馆',team:'pku',x:-19,z:19,type:'teaching' },{ name:'博雅塔',team:'pku',x:-25,z:7,type:'teaching' },
  { name:'北京大学化学学院A区',team:'pku',x:-17.19,z:19.64,type:'teaching' },{ name:'北京大学加速器楼',team:'pku',x:-11.76,z:15.71,type:'teaching' },{ name:'北京大学工学大楼',team:'pku',x:-7.5,z:18.1,type:'teaching' },{ name:'北京大学物理学院',team:'pku',x:-4.1,z:21.4,type:'teaching' },{ name:'北京大学技物楼',team:'pku',x:-1.54,z:20.57,type:'teaching' },
  { name:'百周年纪念讲堂',team:'pku',x:-12,z:27,type:'teaching' },{ name:'北京国际数学研究中心',team:'pku',x:-35,z:5,type:'teaching' },{ name:'文博楼',team:'pku',x:-41,z:8,type:'teaching' },{ name:'生物技术楼',team:'pku',x:-36,z:12,type:'teaching' },
  { name:'李兆基人文学苑',team:'pku',x:-30,z:11,type:'teaching' },{ name:'经济学院',team:'pku',x:-23,z:12,type:'teaching' },{ name:'政府管理大楼',team:'pku',x:-11,z:6,type:'teaching' },{ name:'理科一号楼',team:'pku',x:-16,z:8,type:'teaching' },
  { name:'理科二号楼',team:'pku',x:-12,z:12,type:'teaching' },{ name:'理科三号楼',team:'pku',x:-8,z:8,type:'teaching' },{ name:'第一教学楼',team:'pku',x:-22,z:25,type:'teaching' },{ name:'第二教学楼',team:'pku',x:-17,z:24,type:'teaching' },
  { name:'燕园28楼',team:'pku',x:-39,z:30,type:'dorm' },{ name:'燕园29楼',team:'pku',x:-34,z:30,type:'dorm' },{ name:'燕园30楼',team:'pku',x:-29,z:31,type:'dorm' },{ name:'燕园31楼',team:'pku',x:-24,z:32,type:'dorm' },{ name:'燕园34A楼',team:'pku',x:-18,z:33,type:'dorm' },{ name:'燕园34B楼',team:'pku',x:-12,z:34,type:'dorm' },
  { name:'北京大学畅春园',team:'pku',x:-45.13,z:13.85,type:'dorm' },{ name:'北京大学畅春新园',team:'pku',x:-44.24,z:17.9,type:'dorm' },{ name:'北京大学蔚秀园',team:'pku',x:-46.49,z:10.2,type:'dorm' },{ name:'北京大学承泽园',team:'pku',x:-54.9,z:13.84,type:'teaching' },
  { name:'北京大学中关园',team:'pku',x:-20.8,z:21.75,type:'dorm' },{ name:'北京大学燕东园',team:'pku',x:-18,z:10,type:'teaching' },{ name:'北京大学朗润园',team:'pku',x:-32,z:5.7,type:'teaching' },
  { name:'清华西门',team:'thu',x:-21.5,z:6.9,type:'gate' },{ name:'二校门',team:'thu',x:10,z:1,type:'gate' },{ name:'清华学堂',team:'thu',x:16,z:-5,type:'teaching' },{ name:'大礼堂',team:'thu',x:22,z:-8,type:'teaching' },
  { name:'老图书馆',team:'thu',x:17,z:1,type:'teaching' },{ name:'科学馆',team:'thu',x:12,z:8,type:'teaching' },{ name:'主楼',team:'thu',x:31,z:3,type:'teaching' },{ name:'六教',team:'thu',x:23,z:13,type:'teaching' },
  { name:'新清华学堂',team:'thu',x:28,z:11,type:'teaching' },{ name:'艺术博物馆',team:'thu',x:38,z:14,type:'teaching' },{ name:'综合体育馆',team:'thu',x:25,z:-20,type:'teaching' },{ name:'校医院',team:'thu',x:8,z:15,type:'teaching' },
  { name:'紫荆1号楼',team:'thu',x:30,z:-24,type:'dorm' },{ name:'紫荆2号楼',team:'thu',x:35,z:-24,type:'dorm' },{ name:'紫荆3号楼',team:'thu',x:40,z:-23,type:'dorm' },{ name:'紫荆6号楼',team:'thu',x:29,z:-29,type:'dorm' },{ name:'紫荆9号楼',team:'thu',x:36,z:-29,type:'dorm' },{ name:'求真书院',team:'thu',x:43,z:-29,type:'target' },
  { name:'清华南门',team:'thu',x:22,z:26,type:'gate' },{ name:'清华东南门',team:'thu',x:45,z:22,type:'gate' },
  { name:'清华荷清苑',team:'thu',x:3.47,z:-25.7,type:'dorm' },{ name:'清华双清园',team:'thu',x:26.5,z:-18.2,type:'dorm' },
  { name:'新燕园北门',team:'pku',x:145,z:-16,type:'gate' },{ name:'新燕园教学楼',team:'pku',x:144,z:0,type:'teaching' },
  { name:'新燕园计算机学院',team:'pku',x:137,z:-4,type:'teaching' },{ name:'新燕园集成电路学院',team:'pku',x:153,z:-4,type:'teaching' },
  { name:'新燕园材料学院',team:'pku',x:157,z:4,type:'teaching' },{ name:'新燕园学生公寓',team:'pku',x:135,z:9,type:'dorm' },
  { name:'新燕园馨园食堂',team:'pku',x:147,z:10,type:'teaching' },
  { name:'北大医学部南门',team:'pku',x:215,z:12,type:'gate' },{ name:'医学部逸夫教学楼',team:'pku',x:215.88,z:-.68,type:'teaching' },{ name:'医学图书馆',team:'pku',x:211.88,z:-1.09,type:'teaching' },
  { name:'医学科技楼',team:'pku',x:203.92,z:-6.82,type:'teaching' },{ name:'药学楼',team:'pku',x:211.98,z:1.43,type:'teaching' },{ name:'生化楼',team:'pku',x:210.68,z:-5.96,type:'teaching' },
  { name:'医学部研究生宿舍',team:'pku',x:205.68,z:6.48,type:'dorm' },{ name:'医学部学生公寓',team:'pku',x:216.13,z:-5.14,type:'dorm' },{ name:'医学部体育馆',team:'pku',x:224.95,z:-3.53,type:'teaching' },
  { name:'万柳学区西门',team:'pku',x:258,z:0,type:'gate' },{ name:'万柳公寓一区',team:'pku',x:270,z:-4,type:'dorm' },{ name:'万柳公寓二区',team:'pku',x:274,z:-4,type:'dorm' },{ name:'万柳公寓三区',team:'pku',x:278,z:-4,type:'dorm' },
  { name:'万柳公寓四区',team:'pku',x:270,z:3,type:'teaching' },{ name:'万柳公寓五区',team:'pku',x:275,z:3,type:'teaching' },{ name:'万柳公寓六区',team:'pku',x:280,z:3,type:'teaching' },
];

const osmAliases:Record<string,string>={
  '北京大学加速器楼':'北京大学-加速器楼','北京大学图书馆':'北京大学图书馆','老图书馆':'图书馆老馆','清华西门':'','北大东门':'','北大西门':'',
};
function geolocateSeed(seed:Omit<SiteState,'id'|'stance'|'supply'>){
  if(seed.x>100||seed.type==='gate')return seed;
  const target=osmAliases[seed.name]??seed.name;if(!target)return seed;
  const b=(osmRegions.main.buildings as readonly any[]).find(x=>x.name===target||x.name?.includes(target));if(!b?.points?.length)return seed;
  const x=b.points.reduce((a:number,p:number[])=>a+p[0],0)/b.points.length,z=b.points.reduce((a:number,p:number[])=>a+p[1],0)/b.points.length;
  return {...seed,x:Number(x.toFixed(3)),z:Number(z.toFixed(3))};
}

function makeFreshGame(): GameData {
  const sites: SiteState[] = seeds.map(geolocateSeed).map((s,id)=>({...s,id,stance:'defend',supply:100}));
  const units: UnitState[]=[]; let uid=0;
  sites.forEach(s=>{const count=s.type==='dorm'?(s.team==='pku'?3:2):(s.team==='pku'?4:3);for(let i=0;i<count;i++){const a=i/count*Math.PI*2;units.push({id:uid++,team:s.team,x:s.x+Math.cos(a)*1.25,z:s.z+Math.sin(a)*1.25,tx:s.x,tz:s.z,hp:100,supply:100,siteId:s.id});}});
  return {timeOfDay:8.2,resources:{pku:180,thu:180},deaths:{pku:0,thu:0},sites,units};
}
function readSaves(): Snapshot[]{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'[]') as Snapshot[];}catch{return[];}}

export default function Game3D(){
  const hostRef=useRef<HTMLDivElement>(null);const gameRef=useRef<GameData>(makeFreshGame());const sceneApi=useRef<{sync:()=>void;focus:(region:RegionId)=>void}|null>(null);
  const [saves,setSaves]=useState<Snapshot[]>([]);const [saveOpen,setSaveOpen]=useState(false);const [saveName,setSaveName]=useState('燕园远征');const [autoDay,setAutoDay]=useState(true);const autoDayRef=useRef(true);const [clock,setClock]=useState('08:12');const [selected,setSelected]=useState<number|null>(null);const [region,setRegion]=useState<RegionId>('main');const [notice,setNotice]=useState('拖动己方据点到目标即可下达命令');const [stats,setStats]=useState({pku:0,thu:0,pkuSites:0,thuSites:0});
  const selectedSite=selected==null?null:gameRef.current.sites[selected];
  const refreshSaves=useCallback(()=>setSaves(readSaves().sort((a,b)=>b.savedAt-a.savedAt)),[]);
  useEffect(()=>refreshSaves(),[refreshSaves]);useEffect(()=>{autoDayRef.current=autoDay;},[autoDay]);

  useEffect(()=>{
    const host=hostRef.current;if(!host)return;
    const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.appendChild(renderer.domElement);
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc5d8);scene.fog=new THREE.FogExp2(0x9fc5d8,.007);
    const camera=new THREE.PerspectiveCamera(38,host.clientWidth/host.clientHeight,.1,300);camera.position.set(0,36,34);camera.lookAt(0,0,3);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,3);controls.enableDamping=true;controls.dampingFactor=.08;controls.enableRotate=false;controls.enableZoom=false;controls.enablePan=true;controls.screenSpacePanning=false;controls.mouseButtons.LEFT=THREE.MOUSE.PAN;controls.mouseButtons.MIDDLE=THREE.MOUSE.PAN;controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;controls.touches.ONE=THREE.TOUCH.PAN;
    const hemi=new THREE.HemisphereLight(0xcfe8ff,0x324226,1.9);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff0d0,3.4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;scene.add(sun);const moon=new THREE.DirectionalLight(0x91b7ff,.25);scene.add(moon);
    const mapGroup=new THREE.Group();scene.add(mapGroup);const regions=osmRegions as unknown as Record<string,any>;const regionForX=(x:number)=>x>250?regions.wanliu:x>190?regions.medical:x>100?regions.newYanyuan:regions.main;
    const terrainHeight=(r:any,x:number,z:number)=>{const {cols,rows,heights}=r.terrain,u=THREE.MathUtils.clamp((x-(r.offsetX-r.width/2))/r.width,0,1)*(cols-1),v=THREE.MathUtils.clamp((r.depth/2-z)/r.depth,0,1)*(rows-1),i=Math.floor(u),j=Math.floor(v),fu=u-i,fv=v-j,at=(ii:number,jj:number)=>heights[Math.min(rows-1,jj)*cols+Math.min(cols-1,ii)]||0;return THREE.MathUtils.lerp(THREE.MathUtils.lerp(at(i,j),at(i+1,j),fu),THREE.MathUtils.lerp(at(i,j+1),at(i+1,j+1),fu),fv);};
    const addRegion=(r:any)=>{const {cols,rows,heights}=r.terrain,pos=[],idx=[];for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=r.offsetX-r.width/2+i/(cols-1)*r.width,z=r.depth/2-j/(rows-1)*r.depth;pos.push(x,heights[j*cols+i]||0,z);}for(let j=0;j<rows-1;j++)for(let i=0;i<cols-1;i++){const a=j*cols+i,b=a+1,c=a+cols,d=c+1;idx.push(a,b,c,b,d,c);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();const terrain=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:r.offsetX?0x6d8955:0x718d58,roughness:.98,side:THREE.FrontSide}));terrain.receiveShadow=true;mapGroup.add(terrain);
      const rv:number[]=[],ri:number[]=[];let vi=0;for(const road of r.roads){for(let k=1;k<road.points.length;k++){const [x1,z1]=road.points[k-1],[x2,z2]=road.points[k],dx=x2-x1,dz=z2-z1,len=Math.hypot(dx,dz);if(len<.01)continue;const px=-dz/len*road.width/2,pz=dx/len*road.width/2,y1=terrainHeight(r,x1,z1)+.08,y2=terrainHeight(r,x2,z2)+.08;rv.push(x1+px,y1,z1+pz,x1-px,y1,z1-pz,x2+px,y2,z2+pz,x2-px,y2,z2-pz);ri.push(vi,vi+1,vi+2,vi+2,vi+1,vi+3);vi+=4;}}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.Float32BufferAttribute(rv,3));rg.setIndex(ri);rg.computeVertexNormals();const roads=new THREE.Mesh(rg,new THREE.MeshStandardMaterial({color:0xb7ae98,roughness:.94}));roads.receiveShadow=true;mapGroup.add(roads);
      const box=new THREE.BoxGeometry(1,1,1),bm=new THREE.MeshStandardMaterial({color:r.offsetX?0x9ca6a3:0x8f9998,roughness:.83}),inst=new THREE.InstancedMesh(box,bm,r.buildings.length),dummy=new THREE.Object3D();r.buildings.forEach((b:any,n:number)=>{const xs=b.points.map((p:number[])=>p[0]),zs=b.points.map((p:number[])=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),x=(minX+maxX)/2,z=(minZ+maxZ)/2,w=Math.max(.16,maxX-minX),d=Math.max(.16,maxZ-minZ),h=b.height?Math.min(8,b.height*.65):1.2+(n%5)*.35;dummy.position.set(x,terrainHeight(r,x,z)+h/2,z);dummy.scale.set(w,h,d);dummy.rotation.y=b.points.length>1?Math.atan2(b.points[1][0]-b.points[0][0],b.points[1][1]-b.points[0][1]):0;dummy.updateMatrix();inst.setMatrixAt(n,dummy.matrix);});inst.castShadow=true;inst.receiveShadow=true;mapGroup.add(inst);
      const waterMat=new THREE.MeshStandardMaterial({color:0x47869a,transparent:true,opacity:.78,roughness:.25,metalness:.12});for(const w of r.waters){if(w.points.length<3)continue;const shape=new THREE.Shape();w.points.forEach((p:number[],i:number)=>i?shape.lineTo(p[0],-p[1]):shape.moveTo(p[0],-p[1]));const wm=new THREE.Mesh(new THREE.ShapeGeometry(shape),waterMat);wm.rotation.x=-Math.PI/2;wm.position.y=.1;mapGroup.add(wm);}}
    addRegion(regions.main);addRegion(regions.newYanyuan);addRegion(regions.medical);addRegion(regions.wanliu);
    const addCampusPatch=(x:number,z:number,w:number,d:number,color:number)=>{const p=new THREE.Mesh(new THREE.BoxGeometry(w,.035,d),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.13,depthWrite:false}));p.position.set(x,.13,z);p.renderOrder=1;mapGroup.add(p);};
    addCampusPatch(-36.25,13.5,31.5,43,0xb51f39);addCampusPatch(13.5,-15,70,46,0x713796);
    const buildingGroup=new THREE.Group();scene.add(buildingGroup);const unitGroup=new THREE.Group();scene.add(unitGroup);const commandGroup=new THREE.Group();scene.add(commandGroup);const siteObjects=new Map<number,THREE.Group>();const unitObjects=new Map<number,THREE.Group>();const windowMaterials:THREE.MeshStandardMaterial[]=[];
    const addCommandLine=(a:THREE.Vector3,b:THREE.Vector3,preview=false)=>{const geo=new THREE.BufferGeometry().setFromPoints([a,b]),line=new THREE.Line(geo,new THREE.LineDashedMaterial({color:0xffffff,dashSize:preview?.7:1.1,gapSize:preview?.42:.6,transparent:true,opacity:preview?.65:.95}));line.computeLineDistances();commandGroup.add(line);return line;};
    const rebuildCommandLines=()=>{commandGroup.clear();gameRef.current.sites.forEach(s=>{if(s.orderTarget==null)return;const t=gameRef.current.sites[s.orderTarget];if(!t)return;addCommandLine(new THREE.Vector3(s.x,1.2,s.z),new THREE.Vector3(t.x,1.2,t.z));});};
    const labelTexture=(text:string,color:string)=>{const c=document.createElement('canvas');c.width=512;c.height=96;const x=c.getContext('2d')!;x.fillStyle='rgba(21,30,25,.86)';x.roundRect(4,4,504,88,16);x.fill();x.strokeStyle=color;x.lineWidth=5;x.stroke();x.fillStyle='#fff6dc';x.font='700 34px Microsoft YaHei';x.textAlign='center';x.fillText(text,256,61);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;};
    const rebuildBuildings=()=>{buildingGroup.clear();siteObjects.clear();windowMaterials.splice(0);gameRef.current.sites.forEach(site=>{const g=new THREE.Group(),region=regionForX(site.x);g.position.set(site.x,terrainHeight(region,site.x,site.z),site.z);const isDorm=site.type==='dorm',isTarget=site.type==='target',w=isDorm?1.5:site.type==='gate'?1.15:1.7,d=isDorm?1.05:site.type==='gate' ? .85 : 1.2,h=isDorm?1.9:site.type==='gate'?1.15:isTarget?3.2:2.45;
      const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:isTarget?0xc57c45:isDorm?0xb79b74:0x9da7a7,roughness:.78}));body.position.y=h/2;body.castShadow=true;body.receiveShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,1,4),new THREE.MeshStandardMaterial({color:isTarget?0xffb64d:0x70463b,roughness:.82}));roof.position.y=h+.45;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(roof);
      const wm=new THREE.MeshStandardMaterial({color:0x537080,emissive:0xffc56a,emissiveIntensity:0,roughness:.35});windowMaterials.push(wm);for(let y=.7;y<h-.22;y+=.62)for(const sx of [-1,1]){const win=new THREE.Mesh(new THREE.PlaneGeometry(.28,.21),wm);win.position.set(sx*w*.28,y,d/2+.012);g.add(win);}
      const ring=new THREE.Mesh(new THREE.RingGeometry(.82,1.06,40),new THREE.MeshBasicMaterial({color:TEAM_COLOR[site.team],transparent:true,opacity:.9,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.07;g.add(ring);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:labelTexture(site.name,site.team==='pku'?'#df3b50':'#a569d0'),transparent:true,depthTest:false}));sprite.scale.set(3,.57,1);sprite.position.y=h+.95;g.add(sprite);g.traverse(o=>{o.userData.siteId=site.id;});buildingGroup.add(g);siteObjects.set(site.id,g);});};
    const textureLoader=new THREE.TextureLoader(),emblemTex={pku:textureLoader.load(`${import.meta.env.BASE_URL}pku-seal.svg`),thu:textureLoader.load(`${import.meta.env.BASE_URL}thu-seal.svg`)};emblemTex.pku.colorSpace=THREE.SRGBColorSpace;emblemTex.thu.colorSpace=THREE.SRGBColorSpace;
    const rebuildUnits=()=>{unitGroup.clear();unitObjects.clear();gameRef.current.units.forEach(u=>{const g=new THREE.Group(),region=regionForX(u.x),teamColor=u.team==='pku'?0xc91f3a:0x74429d,bodyMat=new THREE.MeshStandardMaterial({color:teamColor,roughness:.26,metalness:.06,emissive:teamColor,emissiveIntensity:.12});const body=new THREE.Mesh(new THREE.SphereGeometry(.55,24,18),bodyMat);body.position.y=.98;body.castShadow=true;body.receiveShadow=true;g.add(body);const emblem=new THREE.Mesh(new THREE.CircleGeometry(.39,32),new THREE.MeshBasicMaterial({map:emblemTex[u.team],transparent:true,depthWrite:false}));emblem.position.set(0,.98,.515);g.add(emblem);const border=new THREE.Mesh(new THREE.TorusGeometry(.42,.035,8,32),new THREE.MeshStandardMaterial({color:0xfff1d0,roughness:.35}));border.position.set(0,.98,.525);g.add(border);const lm=new THREE.MeshStandardMaterial({color:0x242824,roughness:.8}),lg=new THREE.CylinderGeometry(.055,.055,.68,7);[-1,1].forEach(s=>{const arm=new THREE.Mesh(lg,lm);arm.position.set(s*.54,.9,0);arm.rotation.z=s*.95;g.add(arm);const leg=new THREE.Mesh(lg,lm);leg.position.set(s*.25,.35,0);leg.rotation.z=s*.28;g.add(leg);const hand=new THREE.Mesh(new THREE.SphereGeometry(.09,8,6),lm);hand.position.set(s*.82,.71,0);g.add(hand);});const glow=new THREE.Mesh(new THREE.RingGeometry(.68,.86,28),new THREE.MeshBasicMaterial({color:teamColor,transparent:true,opacity:.7,side:THREE.DoubleSide}));glow.rotation.x=-Math.PI/2;glow.position.y=.05;g.add(glow);g.position.set(u.x,terrainHeight(region,u.x,u.z),u.z);unitGroup.add(g);unitObjects.set(u.id,g);});};
    rebuildBuildings();rebuildUnits();rebuildCommandLines();
    const treeGroup=new THREE.Group();scene.add(treeGroup);let seed=91723;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const tg=new THREE.CylinderGeometry(.14,.2,1.8,7),tm=new THREE.MeshStandardMaterial({color:0x61412f,roughness:1}),cg=new THREE.SphereGeometry(1,10,8),cms=[0x315d36,0x467648,0x5b8a4e].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.92}));for(const [r,count] of [[regions.main,240],[regions.newYanyuan,90],[regions.medical,65],[regions.wanliu,55]] as [any,number][]){for(let i=0;i<count;i++){const x=r.offsetX-r.width/2+rnd()*r.width,z=-r.depth/2+rnd()*r.depth;if(gameRef.current.sites.some(s=>Math.hypot(s.x-x,s.z-z)<3.2)||r.roads.some((road:any)=>road.points.some((p:number[])=>Math.hypot(p[0]-x,p[1]-z)<.8)))continue;const g=new THREE.Group(),tr=new THREE.Mesh(tg,tm);tr.position.y=.9;tr.castShadow=true;g.add(tr);cms.forEach((m,j)=>{const cr=new THREE.Mesh(cg,m);cr.scale.set(1.1-j*.18,.65,1.1-j*.18);cr.position.y=2+j*.62;cr.castShadow=true;g.add(cr);});g.position.set(x,terrainHeight(r,x,z),z);treeGroup.add(g);}}
    const lights:THREE.PointLight[]=[];[[-29,20],[-8,10],[8,8],[19,3],[31,-12],[39,-24],[22,18]].forEach(([x,z])=>{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.05,.07,2.4,6),new THREE.MeshStandardMaterial({color:0x353b37}));pole.position.set(x,1.2,z);scene.add(pole);const bulb=new THREE.Mesh(new THREE.SphereGeometry(.16,8,6),new THREE.MeshStandardMaterial({color:0xffd98e,emissive:0xffb33b,emissiveIntensity:2}));bulb.position.set(x,2.4,z);scene.add(bulb);const l=new THREE.PointLight(0xffc66f,0,11,2);l.position.set(x,2.5,z);scene.add(l);lights.push(l);});
    const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let down:{x:number;y:number;site?:number}|null=null,previewLine:THREE.Line|null=null;const setRay=(ev:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=(ev.clientX-r.left)/r.width*2-1;mouse.y=-(ev.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);};const hitSite=(ev:PointerEvent)=>{setRay(ev);const hit=ray.intersectObjects(buildingGroup.children,true)[0];return hit?.object.userData.siteId as number|undefined;};const groundAt=(ev:PointerEvent)=>{setRay(ev);const p=new THREE.Vector3();return ray.ray.intersectPlane(groundPlane,p)?p:null;};renderer.domElement.addEventListener('pointerdown',e=>{const site=hitSite(e);down={x:e.clientX,y:e.clientY,site};if(site!=null)controls.enabled=false;});renderer.domElement.addEventListener('pointermove',e=>{if(down?.site==null||Math.hypot(e.clientX-down.x,e.clientY-down.y)<8)return;const p=groundAt(e),s=gameRef.current.sites[down.site];if(!p||!s)return;if(previewLine)commandGroup.remove(previewLine);previewLine=addCommandLine(new THREE.Vector3(s.x,1.2,s.z),new THREE.Vector3(p.x,1.2,p.z),true);});renderer.domElement.addEventListener('pointerup',e=>{if(!down)return;controls.enabled=true;if(previewLine){commandGroup.remove(previewLine);previewLine=null;}const end=hitSite(e),moved=Math.hypot(e.clientX-down.x,e.clientY-down.y)>8;if(!moved&&down.site!=null)setSelected(down.site);if(moved&&down.site!=null&&end!=null&&end!==down.site){const source=gameRef.current.sites[down.site],target=gameRef.current.sites[end];if(source.team==='pku'){source.orderTarget=target.id;const troops=gameRef.current.units.filter(u=>u.team==='pku'&&u.siteId===source.id);troops.forEach(u=>{u.targetSiteId=target.id;u.tx=target.x+(u.id%5-2)*.35;u.tz=target.z+(u.id%4-1.5)*.35;});rebuildCommandLines();setNotice(troops.length?`${source.name} → ${target.name}：${troops.length}支小队出发`:`${source.name}暂无可调动兵力`);}else setNotice('只能从北大控制的据点发出命令');}down=null;});
    let raf=0,last=performance.now(),statAt=0;const animate=(now:number)=>{raf=requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;const g=gameRef.current;if(autoDayRef.current)g.timeOfDay=(g.timeOfDay+dt*.08)%24;const angle=(g.timeOfDay-6)/24*Math.PI*2,day=THREE.MathUtils.smoothstep(Math.sin(angle),-.12,.35),night=1-day;sun.position.set(Math.cos(angle)*55,Math.max(-4,Math.sin(angle)*55),25);sun.intensity=day*3.4;moon.position.set(-sun.position.x,Math.max(10,-sun.position.y),-25);moon.intensity=night*.6;hemi.intensity=.18+day*1.72;hemi.color.set(day>.35?0xcfe8ff:0x29436e);hemi.groundColor.set(day>.35?0x324226:0x101721);const sky=new THREE.Color(0x07101f).lerp(new THREE.Color(0x9fc5d8),day);scene.background=sky;(scene.fog as THREE.FogExp2).color.copy(sky);windowMaterials.forEach(m=>m.emissiveIntensity=night*3.2);lights.forEach(l=>l.intensity=night*15);renderer.toneMappingExposure=.72+day*.38;
      g.units.forEach(u=>{const mesh=unitObjects.get(u.id);if(!mesh)return;const dx=u.tx-u.x,dz=u.tz-u.z,dist=Math.hypot(dx,dz);if(dist>.18){const s=1.25*dt;u.x+=dx/dist*s;u.z+=dz/dist*s;mesh.position.set(u.x,terrainHeight(regionForX(u.x),u.x,u.z),u.z);mesh.rotation.y=Math.atan2(dx,dz);}});if(now-statAt>500){statAt=now;setStats({pku:g.units.filter(u=>u.team==='pku').length,thu:g.units.filter(u=>u.team==='thu').length,pkuSites:g.sites.filter(s=>s.team==='pku').length,thuSites:g.sites.filter(s=>s.team==='thu').length});const h=Math.floor(g.timeOfDay),m=Math.floor(g.timeOfDay%1*60);setClock(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);}controls.update();renderer.render(scene,camera);};raf=requestAnimationFrame(animate);
    const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();};addEventListener('resize',resize);sceneApi.current={sync:()=>{rebuildBuildings();rebuildUnits();rebuildCommandLines();},focus:(r)=>{const x={main:0,newYanyuan:145,medical:215,wanliu:275}[r];controls.target.set(x,0,0);camera.position.set(x,36,34);controls.update();}};return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);controls.dispose();renderer.dispose();if(renderer.domElement.parentNode===host)host.removeChild(renderer.domElement);};
  },[]);

  const saveGame=()=>{const name=saveName.trim()||`存档 ${new Date().toLocaleString('zh-CN')}`,snapshot:Snapshot={version:1,name,savedAt:Date.now(),...structuredClone(gameRef.current)},next=[snapshot,...readSaves().filter(s=>s.name!==name)].slice(0,12);localStorage.setItem(SAVE_KEY,JSON.stringify(next));refreshSaves();};
  const loadGame=(save:Snapshot)=>{const {timeOfDay,resources,deaths,sites,units}=structuredClone(save);gameRef.current={timeOfDay,resources,deaths,sites,units};sceneApi.current?.sync();setSelected(null);setSaveOpen(false);};
  const deleteSave=(savedAt:number)=>{const next=readSaves().filter(s=>s.savedAt!==savedAt);localStorage.setItem(SAVE_KEY,JSON.stringify(next));setSaves(next);};
  const newGame=()=>{gameRef.current=makeFreshGame();sceneApi.current?.sync();setSelected(null);};
  const stanceText=useMemo(()=>({defend:'🛡 防守',guard:'📡 守卫',standby:'⏸ 待命'}),[]);const setStance=(s:Stance)=>{if(!selectedSite||selectedSite.team!=='pku')return;selectedSite.stance=s;setSelected(selectedSite.id);};
  return <main className="game-shell"><div ref={hostRef} className="webgl-stage"/><header className="hud-top"><div><h1>燕园远征：求真书院</h1><p>OSM导航级路网 · WebGL地形版</p></div><div className="time-pill"><span>{clock}</span><button onClick={()=>setAutoDay(v=>!v)}>{autoDay?'自动昼夜':'时间暂停'}</button></div><button className="save-main" onClick={()=>{refreshSaves();setSaveOpen(true);}}>存档管理</button></header><nav className="region-switch"><button className={region==='main'?'active':''} onClick={()=>{setRegion('main');sceneApi.current?.focus('main');setNotice('已进入燕园—清华园主战场');}}>燕园—清华园</button><button className={region==='newYanyuan'?'active':''} onClick={()=>{setRegion('newYanyuan');sceneApi.current?.focus('newYanyuan');setNotice('已进入北大新燕园校区');}}>北大新燕园</button></nav><div className="command-notice">{notice}</div><aside className="war-overview"><h2>总体战况</h2><div className="stat-grid"><span>总兵力</span><b className="red">{stats.pku}</b><b className="purple">{stats.thu}</b><span>控制据点</span><b className="red">{stats.pkuSites}</b><b className="purple">{stats.thuSites}</b><span>战略资源</span><b className="red">{Math.floor(gameRef.current.resources.pku)}</b><b className="purple">{Math.floor(gameRef.current.resources.thu)}</b><span>累计阵亡</span><b className="red">{gameRef.current.deaths.pku}</b><b className="purple">{gameRef.current.deaths.thu}</b></div><button onClick={newGame}>重新开始</button></aside>
    <nav className="region-extra"><button className={region==='medical'?'active':''} onClick={()=>{setRegion('medical');sceneApi.current?.focus('medical');setNotice('已进入北大医学部—学院路片区');}}>北大医学部</button><button className={region==='wanliu'?'active':''} onClick={()=>{setRegion('wanliu');sceneApi.current?.focus('wanliu');setNotice('已进入北大万柳学区');}}>北大万柳</button></nav>
    {selectedSite&&<section className="site-menu"><strong>{selectedSite.name}</strong><p className={selectedSite.team==='pku'?'red':'purple'}>{selectedSite.team==='pku'?'北大控制':'清华控制'} · 补给 {Math.round(selectedSite.supply)}</p><div>{(Object.keys(stanceText) as Stance[]).map(s=><button key={s} className={selectedSite.stance===s?'active':''} disabled={selectedSite.team!=='pku'} onClick={()=>setStance(s)}>{stanceText[s]}</button>)}</div><small>从此据点拖向友方可增援，拖向敌方可进攻</small></section>}
    <div className="day-slider"><span>昼夜</span><input aria-label="时间" type="range" min="0" max="24" step=".1" value={gameRef.current.timeOfDay} onChange={e=>{gameRef.current.timeOfDay=Number(e.target.value);setAutoDay(false);setClock(`${String(Math.floor(Number(e.target.value))).padStart(2,'0')}:00`);}}/></div>
    <div className="map-attribution">道路与建筑 © OpenStreetMap contributors · 高程 Open-Meteo</div>
    {saveOpen&&<div className="modal-backdrop" onMouseDown={()=>setSaveOpen(false)}><section className="save-modal" onMouseDown={e=>e.stopPropagation()}><div className="save-head"><div><small>本机存档</small><h2>战局档案馆</h2></div><button onClick={()=>setSaveOpen(false)}>×</button></div><div className="new-save"><input value={saveName} maxLength={24} onChange={e=>setSaveName(e.target.value)} placeholder="输入存档名称"/><button onClick={saveGame}>保存当前战局</button></div><div className="save-list">{!saves.length&&<p className="empty">暂无存档</p>}{saves.map(s=><article key={s.savedAt}><div><strong>{s.name}</strong><span>{new Date(s.savedAt).toLocaleString('zh-CN')} · {s.units.length}人 · {s.timeOfDay.toFixed(1)}时</span></div><button className="enter" onClick={()=>loadGame(s)}>进入</button><button className="delete" onClick={()=>deleteSave(s.savedAt)}>删除</button></article>)}</div><p className="save-note">存档保存在当前浏览器的本地存储中；清除浏览器数据会一并删除。</p></section></div>}
  </main>;
}
