import assert from "node:assert/strict";
import {readFileSync,statSync} from "node:fs";
import {createHash} from "node:crypto";
import {makeFreshGame,pointInPolygon} from "../src/game/create-game";
import {REAL_CAMPUS_BUILDINGS,REAL_CAMPUS_LANDMARKS} from "../src/game/real-campus-data";
import {REAL_CAMPUS_SOURCES} from "../src/game/real-campus-sources";
import {SATELLITE_ROOF_COLORS} from "../src/game/real-campus-satellite-colors";
import {SATELLITE_TREE_POINTS} from "../src/game/real-campus-satellite-trees";
import {osmRegions} from "../src/osm-map-data-real";
import {osmRegions as classicRegions} from "../src/osm-map-data";
import {buildKernelNavGrid} from "../src/game/kernel/build-navigation";
import {createKernel,navPoint,nearestOpenIndex} from "../src/game/kernel";

const region:any=osmRegions.main,campuses=region.campuses.filter((c:any)=>c.name==="北京大学"||c.name==="清华大学");
const campusBuildings=region.buildings.filter((building:any)=>{
  const x=building.points.reduce((sum:number,p:number[])=>sum+p[0],0)/building.points.length,z=building.points.reduce((sum:number,p:number[])=>sum+p[1],0)/building.points.length;
  return campuses.some((campus:any)=>pointInPolygon(x,z,campus.points));
});
assert.equal(campusBuildings.length,925);
assert.equal(region.terrain.cols,72);assert.equal(region.terrain.rows,72);
assert.ok(region.hardscapes.length>200&&region.trees.length>300&&region.treeRows.length>100,"satellite/OSM surface detail is incomplete");
assert.ok(Object.keys(SATELLITE_ROOF_COLORS).length>=800,"satellite roof-color coverage regressed");
assert.ok(SATELLITE_TREE_POINTS.pku.length>2000&&SATELLITE_TREE_POINTS.thu.length>5000,"satellite canopy coverage regressed");
assert.equal(REAL_CAMPUS_BUILDINGS.length,925);
assert.equal(new Set(REAL_CAMPUS_BUILDINGS.map(item=>item.key)).size,925);
assert.equal(REAL_CAMPUS_LANDMARKS.length,143);
assert.equal(new Set(REAL_CAMPUS_LANDMARKS.map(item=>item.siteId)).size,143);
assert.ok(REAL_CAMPUS_BUILDINGS.every(item=>item.heightMeters>2&&item.levels>0&&item.facadeColor&&item.roofColor&&item.sourceIds.length>=5&&item.photoSearch));
assert.ok(REAL_CAMPUS_LANDMARKS.every(item=>item.key&&item.features.length&&item.photoReferenceChannels.length>=3&&item.photoSearch&&Object.values(item.photoAngles).every(value=>value==="pending-verification"||value==="verified")));
const sourceIds=new Set(REAL_CAMPUS_SOURCES.map(source=>source.id));
const sourced=[...(REAL_CAMPUS_BUILDINGS as readonly {name:string;sourceIds:readonly string[]}[]),...(REAL_CAMPUS_LANDMARKS as readonly {name:string;sourceIds:readonly string[]}[])];
for(const item of sourced)for(const source of item.sourceIds)assert.ok(sourceIds.has(source),`${item.name}: unknown source ${source}`);
const real=makeFreshGame("real-campus-v1"),classic=makeFreshGame("classic"),grid=buildKernelNavGrid(region),classicGrid=buildKernelNavGrid(classicRegions.main);
assert.equal(real.campaign.mapProfile,"real-campus-v1");assert.equal(classic.campaign.mapProfile,"classic");
assert.ok(real.sites.every(site=>site.osmKey&&nearestOpenIndex(grid,site.x,site.z)>=0),"a gameplay landmark cannot reach the navigation grid");
delete classic.campaign.mapProfile;delete classic.campaign.mapGeometryVersion;
assert.equal(createKernel(classic,{navGrid:classicGrid,aiTeams:[]}).snapshot().state.campaign.mapProfile,"classic");
const newlyBlocked=grid.blocked.findIndex((blocked,index)=>blocked>0&&!classicGrid.blocked[index]);
assert.ok(newlyBlocked>=0,"test requires an obstacle added by the 2026 geometry");
const [blockedX,blockedZ]=navPoint(grid,newlyBlocked),unit=classic.units[0],target=classic.sites.find(site=>!site.destroyed&&site.id!==unit.siteId)!;
Object.assign(unit,{x:blockedX,z:blockedZ,tx:target.x,tz:target.z,targetSiteId:target.id,path:[[blockedX,blockedZ],[target.x,target.z]],pathIndex:0,transport:"bike",movementOrder:{team:unit.team,goalSiteId:target.id,goalX:target.x,goalZ:target.z,purpose:"combat"}});
const upgraded=createKernel(classic,{navGrid:grid,aiTeams:[],mapProfile:"real-campus-v1"}).snapshot().state,upgradedUnit=upgraded.units.find(value=>value.id===unit.id)!;
assert.equal(upgraded.campaign.mapProfile,"real-campus-v1");
assert.ok(upgradedUnit.x!==blockedX||upgradedUnit.z!==blockedZ,"unit embedded in a new building was not migrated");
assert.equal(upgradedUnit.targetSiteId,target.id);assert.equal(upgradedUnit.movementOrder?.goalSiteId,target.id);assert.equal(upgradedUnit.transport,"bike");assert.ok(upgradedUnit.path?.length,"upgraded order was not rerouted");
const classicMapBytes=readFileSync(new URL("../src/osm-map-data.ts",import.meta.url));
assert.equal(createHash("sha256").update(classicMapBytes).digest("hex"),"9fa0cdf37e6bb77974c352b0d1de1f55bcefff0560bc2b890e9fc52abf518795","classic geometry changed from v0.3.13");
const renderer=readFileSync(new URL("../src/game/engine/use-battlefield.ts",import.meta.url),"utf8");
assert.ok(renderer.includes("REAL_BUILDING_BY_KEY")&&renderer.includes("namedRoadAt")&&renderer.includes("water.level - 0.08")&&renderer.includes("fallbackLevels")&&renderer.includes("const roofVertex")&&renderer.includes("realCampus ? wallTone.r : roofTone.r")&&!renderer.includes("onVehicleSurface"));
for(const asset of ["campus-grass-albedo.webp","campus-asphalt-albedo.webp","campus-paving-albedo.webp","campus-facade-detail.webp","campus-water-normal.webp"])assert.ok(statSync(new URL(`../public/materials/${asset}`,import.meta.url)).size>500,`${asset} missing`);
console.log("PASS: 925 campus buildings, 143 landmarks, satellite/OSM surfaces, 72x72 terrain, carved water, metre-scale buildings, connected roads, PBR materials and map compatibility");
