import assert from "node:assert/strict";
import {readFileSync,statSync} from "node:fs";
import {createHash} from "node:crypto";
import {makeFreshGame,pointInPolygon} from "../src/game/create-game";
import {REAL_CAMPUS_BUILDINGS,REAL_CAMPUS_LANDMARKS} from "../src/game/real-campus-data";
import {REAL_CAMPUS_SOURCES} from "../src/game/real-campus-sources";
import {SATELLITE_ROOF_COLORS} from "../src/game/real-campus-satellite-colors";
import {SATELLITE_TREE_POINTS} from "../src/game/real-campus-satellite-trees";
import {osmRegions} from "../src/osm-map-data-real";
import {osmRegions as classicRegions} from "../src/osm-map-data";
import {buildKernelNavGrid} from "../src/game/kernel/build-navigation";
import {createKernel,navPoint,nearestOpenIndex} from "../src/game/kernel";
import {MAP_PROFILES} from "../src/game/map-profile";

const region:any=osmRegions.main,campuses=region.campuses.filter((c:any)=>c.name==="北京大学"||c.name==="清华大学");
const campusBuildings=region.buildings.filter((building:any)=>{
  const x=building.points.reduce((sum:number,p:number[])=>sum+p[0],0)/building.points.length,z=building.points.reduce((sum:number,p:number[])=>sum+p[1],0)/building.points.length;
  return campuses.some((campus:any)=>pointInPolygon(x,z,campus.points));
});
assert.equal(campusBuildings.length,925);
assert.equal(region.terrain.cols,72);assert.equal(region.terrain.rows,72);
assert.ok(region.hardscapes.length>200&&region.trees.length>300&&region.treeRows.length>100,"satellite/OSM surface detail is incomplete");
assert.ok(region.waters.some((water:any)=>water.holes?.length),"OSM water relation holes are missing");
for(const building of region.buildings){const x=building.points.reduce((sum:number,p:number[])=>sum+p[0],0)/building.points.length,z=building.points.reduce((sum:number,p:number[])=>sum+p[1],0)/building.points.length;assert.ok(!region.waters.some((water:any)=>pointInPolygon(x,z,water.points)&&!(water.holes??[]).some((hole:number[][])=>pointInPolygon(x,z,hole))),`${building.osmType}/${building.osmId} remains inside rendered water`);}
assert.ok(Object.keys(SATELLITE_ROOF_COLORS).length>=800,"satellite roof-color coverage regressed");
assert.ok(SATELLITE_TREE_POINTS.pku.length>2000&&SATELLITE_TREE_POINTS.thu.length>5000,"satellite canopy coverage regressed");
assert.equal(REAL_CAMPUS_BUILDINGS.length,925);
assert.equal(new Set(REAL_CAMPUS_BUILDINGS.map(item=>item.key)).size,925);
assert.equal(REAL_CAMPUS_LANDMARKS.length,143);
assert.deepEqual(MAP_PROFILES.map(profile=>profile.id),["real-campus-v1"]);
assert.equal(new Set(REAL_CAMPUS_LANDMARKS.map(item=>item.siteId)).size,143);
assert.ok(REAL_CAMPUS_BUILDINGS.every(item=>item.heightMeters>2&&item.levels>0&&item.facadeColor&&item.roofColor&&item.sourceIds.length>=5&&item.photoSearch));
assert.ok(REAL_CAMPUS_LANDMARKS.every(item=>item.key&&item.features.length&&item.photoReferenceChannels.length>=3&&item.photoSearch&&Object.values(item.photoAngles).every(value=>value==="pending-verification"||value==="verified")));
const sourceIds=new Set(REAL_CAMPUS_SOURCES.map(source=>source.id));
const sourced=[...(REAL_CAMPUS_BUILDINGS as readonly {name:string;sourceIds:readonly string[]}[]),...(REAL_CAMPUS_LANDMARKS as readonly {name:string;sourceIds:readonly string[]}[])];
for(const item of sourced)for(const source of item.sourceIds)assert.ok(sourceIds.has(source),`${item.name}: unknown source ${source}`);
const real=makeFreshGame("real-campus-v1"),classic=makeFreshGame("classic"),grid=buildKernelNavGrid(region),classicGrid=buildKernelNavGrid(classicRegions.main);
assert.equal(real.campaign.mapProfile,"real-campus-v1");assert.equal(classic.campaign.mapProfile,"classic");
assert.ok(real.sites.every(site=>site.osmKey&&nearestOpenIndex(grid,site.x,site.z)>=0),"a gameplay landmark cannot reach the navigation grid");
delete classic.campaign.mapProfile;delete classic.campaign.mapGeometryVersion;
assert.equal(createKernel(classic,{navGrid:grid,aiTeams:[]}).snapshot().state.campaign.mapProfile,"real-campus-v1");
const newlyBlocked=grid.blocked.findIndex((blocked,index)=>blocked>0&&!classicGrid.blocked[index]);
assert.ok(newlyBlocked>=0,"test requires an obstacle added by the 2026 geometry");
const [blockedX,blockedZ]=navPoint(grid,newlyBlocked),unit=classic.units[0],target=classic.sites.find(site=>!site.destroyed&&site.id!==unit.siteId)!;
Object.assign(unit,{x:blockedX,z:blockedZ,tx:target.x,tz:target.z,targetSiteId:target.id,path:[[blockedX,blockedZ],[target.x,target.z]],pathIndex:0,transport:"bike",movementOrder:{team:unit.team,goalSiteId:target.id,goalX:target.x,goalZ:target.z,purpose:"combat"}});
const upgraded=createKernel(classic,{navGrid:grid,aiTeams:[],mapProfile:"real-campus-v1"}).snapshot().state,upgradedUnit=upgraded.units.find(value=>value.id===unit.id)!;
assert.equal(upgraded.campaign.mapProfile,"real-campus-v1");
assert.ok(upgradedUnit.x!==blockedX||upgradedUnit.z!==blockedZ,"unit embedded in a new building was not migrated");
assert.equal(upgradedUnit.targetSiteId,target.id);assert.equal(upgradedUnit.movementOrder?.goalSiteId,target.id);assert.equal(upgradedUnit.transport,"bike");assert.ok(upgradedUnit.path?.length,"upgraded order was not rerouted");
const classicMapText=readFileSync(new URL("../src/osm-map-data.ts",import.meta.url),"utf8").replace(/\r\n/g,"\n");
assert.equal(createHash("sha256").update(classicMapText).digest("hex"),"90f2b492cb92f63d6066122fe9c15c971db836e34ab09e2603d38d98f1d2b13b","classic geometry changed from v0.3.13");
const renderer=readFileSync(new URL("../src/game/engine/use-battlefield.ts",import.meta.url),"utf8");
const homeScreen=readFileSync(new URL("../src/game/ui/home-screen.tsx",import.meta.url),"utf8"),hubPage=readFileSync(new URL("../native-server/plugins/account-hub/static/index.html",import.meta.url),"utf8");
assert.ok(!homeScreen.includes("升级真实地图")&&!hubPage.includes('<option value="classic">'),"classic map remains selectable");
assert.ok(renderer.includes("REAL_BUILDING_BY_KEY")&&renderer.includes("namedRoadAt")&&renderer.includes("water.holes")&&renderer.includes("water.level + 0.035")&&renderer.includes("buildingSurfaceMaterials")&&renderer.includes("THREE.FrontSide")&&renderer.includes("hoveredRoadName")&&renderer.includes("showSiteLabels = true")&&renderer.includes("teamName = site.team")&&renderer.includes("fallbackLevels")&&renderer.includes("const roofVertex")&&renderer.includes("realCampus ? wallTone.r : roofTone.r")&&renderer.includes("applyCampusSurface")&&renderer.includes("campusSurfaceMask")&&renderer.includes("campusGrassUvB")&&renderer.includes("applyCampusBuildingSurface")&&renderer.includes("campusRoofFactor")&&renderer.includes("campusTextures?.surfaceMask && !road.bridge")&&renderer.includes("treeCrownClusters")&&renderer.includes("campusTextures?.track")&&renderer.includes("campusTextures?.water")&&renderer.includes("lampGlowMaterial")&&renderer.includes("spacing = realCampus ? 0.72 : 3.1")&&renderer.includes("nearestLamps")&&renderer.includes("distance<18")&&renderer.includes("localDistance<12")&&renderer.includes("distance < 22 && daytime")&&!renderer.includes("onVehicleSurface"));
assert.ok(!renderer.includes("length * 0.94, 0.03, depth * 0.92, roof"),"generic dormitory roof plate returned");
assert.ok(!renderer.includes("depth * (0.53 + step * 0.025)"),"detached library step plate returned");
assert.ok(!renderer.includes("base + height + 0.025 + tier * 0.025"),"detached auditorium roof tiers returned");
for(const asset of ["campus-grass-albedo.webp","campus-leaf-albedo.webp","campus-leaf-roughness.webp","campus-asphalt-albedo.webp","campus-track-albedo.webp","campus-track-roughness.webp","campus-paving-albedo.webp","campus-facade-detail.webp","campus-roof-detail.webp","campus-roof-roughness.webp","campus-water-albedo.webp","campus-water-normal.webp","campus-macro-variation.webp","campus-surface-mask.png"])assert.ok(statSync(new URL(`../public/materials/${asset}`,import.meta.url)).size>500,`${asset} missing`);
console.log("PASS: 925 campus buildings, 143 landmarks, unified terrain/road surface, cohesive vegetation/water/sport materials, carved water, metre-scale buildings, connected roads and map compatibility");
